info:
  contact: {}
  license: {}
paths:
  /v1/user/{name}:
    get:
      description: 保存用户
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":200,"data":result,"msg":"success"}
          schema:
            type: object
        "400":
          description: code":400,"data":,"msg":"failed"}
          schema:
            type: object
      summary: 保存用户
      tags:
      - 保存用户
swagger: "2.0"
